# Generated by Django 4.1.7 on 2023-03-31 00:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Detail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fichier', models.FileField(max_length=255, upload_to='uploads/')),
            ],
        ),
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=255)),
                ('fichier_CV', models.FileField(max_length=255, upload_to='uploads/')),
                ('fichier_photo', models.ImageField(max_length=255, upload_to='media/')),
                ('lien_linkedln', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255)),
                ('type', models.CharField(choices=[('dg', 'Design Graphique'), ('pa', 'Production Audiovisuelle'), ('c3d', 'Conception 3D')], default='dg', max_length=255)),
                ('details', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.detail')),
            ],
        ),
        migrations.CreateModel(
            name='Equipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('personnels', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.personnel')),
            ],
        ),
        migrations.CreateModel(
            name='Projet',
            fields=[
                ('libelle', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('date_debut', models.DateField()),
                ('date_fin', models.DateField()),
                ('acheve', models.BooleanField(default=False)),
                ('equipe', models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='ArtyProd.equipe')),
                ('services', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.service')),
            ],
        ),
    ]
