# Generated by Django 4.1.7 on 2023-04-01 00:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0002_remove_equipe_personnels_equipe_personnels'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='id',
            field=models.BigAutoField(auto_created=True, default=0, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='projet',
            name='equipe',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.equipe'),
        ),
    ]
