# Generated by Django 4.1.7 on 2023-05-01 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0003_projet_id_alter_projet_equipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='status',
            field=models.CharField(choices=[('P', 'Pending'), ('A', 'Approved')], default='P', max_length=1),
        ),
    ]
