# Generated by Django 4.1.7 on 2023-05-01 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0004_projet_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
