# Generated by Django 4.1.7 on 2023-05-05 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0007_user'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
