# Generated by Django 4.1.7 on 2023-05-05 19:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0009_customuser'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.customuser'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='user',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='ArtyProd.customuser'),
        ),
    ]
