# Generated by Django 4.1.7 on 2023-05-06 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0010_alter_client_user_alter_personnel_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=8),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fichier_CV',
            field=models.FileField(default=None, max_length=255, upload_to='uploads/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='fichier_photo',
            field=models.ImageField(default=None, max_length=255, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='lien_linkedln',
            field=models.CharField(default=None, max_length=255),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='nom',
            field=models.CharField(default=None, max_length=255),
        ),
    ]
