# Generated by Django 4.1.7 on 2023-05-06 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0012_alter_personnel_lien_linkedln'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='nom',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='personnel',
            name='nom',
            field=models.CharField(max_length=255),
        ),
    ]
