# Generated by Django 4.1.7 on 2023-05-06 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0013_alter_client_nom_alter_personnel_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='email',
            field=models.EmailField(default='', max_length=255),
        ),
    ]
