# Generated by Django 4.1.7 on 2023-05-09 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0014_alter_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='telephone',
            field=models.DecimalField(decimal_places=2, max_digits=8),
        ),
    ]
