# Generated by Django 4.1.7 on 2023-05-12 19:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0015_alter_client_telephone'),
    ]

    operations = [
        migrations.AddField(
            model_name='projet',
            name='avisn',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=999),
        ),
        migrations.AddField(
            model_name='projet',
            name='avisp',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=999),
        ),
    ]
