# Generated by Django 4.1.7 on 2023-05-12 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ArtyProd', '0016_projet_avisn_projet_avisp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projet',
            name='avisn',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999),
        ),
        migrations.AlterField(
            model_name='projet',
            name='avisp',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=999),
        ),
    ]
